version: '3.3'
services:
  build-deck-frontend:
    image: "alpine"
    container_name: build-deck-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always